name: Build and Push Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      BACKEND_API_URL:
        description: 'Backend API URL'
        required: true
        default: 'http://localhost:8081'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/huseinj/my-svelte-app

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build Docker image
      - name: Build Docker image
          run: |
            docker build \
            --build-arg BACKEND_API_URL=${{ github.event.inputs.BACKEND_API_URL }} \
            -t $IMAGE_NAME:latest .

      # 4. Push Docker image
      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest
